language: r
bioc_required: true

after_script:
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - ./travis-tool.sh install_bioc BiocCheck
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"

notifications:
  email:
    on_failure: ps562@cam.ac.uk
