language: r
sudo: false
cache: packages
latex: false

r: 
  - bioc-devel
  - bioc-release

os:
  - linux
  - osx
  
r_packages:
  - covr

bioc_required: true
bioc_packages:
  - BiocCheck
  - GenomeInfoDbData


after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"
  
after_success:
  - Rscript -e 'library(covr);package_coverage()'
  - Rscript -e 'library(covr);codecov()'

notifications:
  email:
    on_failure: ps562@cam.ac.uk
